---
- hosts: "{{ hosts }}"
  tasks:
    - name: conecta a apache?
      block:
        - win_uri:
            url: http://{{ hosts }}
      rescue:
        - debug:
            msg: "Debes levantar el apache"
      always:
        - debug:
            msg: "Siempre ejecuto esto"

