---
- hosts: "{{ hosts }}"
  tasks:
    - name: creamos un directorio temporal
      win_file:
        path: c:\temp
        state: directory
    - name: descargamos el software
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\Temp
    - name: Install MSI of Apache
      win_package:
        path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
        state: present
    - name: configuramos email administrador
      win_lineinfile:
        path: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\httpd.conf
        regex: '^ServerAdmin'
        line: 'ServerAdmin roberto@windows.com'
